/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package productos.quimicos;

/**
 *
 * @author User
 */
public class productosquimicos extends javax.swing.JPanel {
int Litros=1, Agua=1, Sales=1,Detergente=1, Densidad=1
    /**
     * Creates new form productosquimicos
     */
    public productosquimicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        slLitros = new javax.swing.JSlider();
        lblCantidad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDetergente = new javax.swing.JSlider();
        lblresultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDensidad = new javax.swing.JSlider();
        lblevidencia = new javax.swing.JLabel();
        lblAgua = new javax.swing.JLabel();
        lblsales = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(null, null));

        jLabel1.setText("Litros a Fabricar");

        slLitros.setMajorTickSpacing(5);
        slLitros.setPaintLabels(true);
        slLitros.setPaintTicks(true);
        slLitros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slLitrosStateChanged(evt);
            }
        });

        lblCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));

        jLabel3.setText("Calidad de Detergente");

        lblDetergente.setMajorTickSpacing(1);
        lblDetergente.setMaximum(10);
        lblDetergente.setPaintLabels(true);
        lblDetergente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lblDetergenteStateChanged(evt);
            }
        });

        lblresultado.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));

        jLabel5.setText("Densidad");

        lblDensidad.setMajorTickSpacing(50);
        lblDensidad.setMaximum(200);
        lblDensidad.setMinimum(50);
        lblDensidad.setMinorTickSpacing(100);
        lblDensidad.setPaintLabels(true);
        lblDensidad.setPaintTicks(true);
        lblDensidad.setValue(100);
        lblDensidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lblDensidadStateChanged(evt);
            }
        });

        lblevidencia.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));

        lblAgua.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));
        lblAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAguaMouseClicked(evt);
            }
        });

        lblsales.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));
        lblsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(lblsales, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lblDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblevidencia, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(lblresultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(slLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblevidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblsales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAgua, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slLitrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slLitrosStateChanged
        // TODO add your handling code here:
      Litros=slLitros.getValue();
      lblCantidad.setText("los litros son"+slLitros.getValue());
      Agua=2*Litros+(Detergente/Densidad);
      Sales=(Detergente*Litros)/(100*Densidad);
      lblAgua.setText("los litros son: "+Agua);
      lblsales.setText("los litros son: "+Sales);
    }//GEN-LAST:event_slLitrosStateChanged

    private void lblDetergenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lblDetergenteStateChanged
        // TODO add your handling code here:
     =Detergente.getvalue();
     lblresultado.setText("el detergente es:"+lbldetergente.getvalue());
    }//GEN-LAST:event_lblDetergenteStateChanged

    private void lblDensidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lblDensidadStateChanged
        // TODO add your handling code here:
        lblevidencia=lbldensidad.getvalue();
        lblevidencia.setText("la densidad es:"+lbldensidad.getvalue());
    }//GEN-LAST:event_lblDensidadStateChanged

    private void lblAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAguaMouseClicked
        // TODO add your handling code here:
        lblagua=2*lbllitros+(lbldetergente/lbldensidad);
    }//GEN-LAST:event_lblAguaMouseClicked

    private void lblsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalesMouseClicked
        // TODO add your handling code here:
        lblsales=(lbldetergente*lbllitros)/(100*lbldensidad);
    }//GEN-LAST:event_lblsalesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JSlider lblDensidad;
    private javax.swing.JSlider lblDetergente;
    private javax.swing.JLabel lblevidencia;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JLabel lblsales;
    private javax.swing.JSlider slLitros;
    // End of variables declaration//GEN-END:variables
}
